---
title: "Mandelbrot"
author: "Bram van Smoorenburg"
date: "20 March 2018"
output: html_document
---

#the basics

basic input
```{r}
legheight=10
height=200
width=200
limit=200
clusters=6
```

start and end
```{r}
if (width>height) {
  starttopleft=c(-2*width/height,2)
  startbotright=c(2*width/height,-2)
} else {
  starttopleft=c(-2,2*height/width)
  startbotright=c(2,-2*height/width)
}
endpoint=c(-1.257368028466541028848015443311845631781836978663072281140249031956410402494751180,0.378730831028625370052982615184932400328597164069352539853482366028096283069779030622959)
fraction=0.7
```

new directory
```{r}
dir.create("./Mandelbrot Set Output")
```

library
```{r}
library(png)
library(abind)
library(parallel)
source("C:/Users/bramv/OneDrive/Documents/R shit/15digs.R")
```

legend colors
1=white
2=red
3=yellow
4=green
5=light blue
6=dark blue
7=purple
8=black
```{r}
cols2=cbind(c(1,1,1),c(1,0,0),c(1,1,0),c(0,1,0),c(0,1,1),c(0,0,1),c(1,0,1),c(0,0,0))
colfunc=function(vec,totcol,cols=cols2) {
  if (length(vec)>totcol) {
    stop("too many colors")
  } else if (length(vec)==totcol) {
    return(cols[,vec])
  }
  
  colloc=round(seq(1,totcol,length.out = length(vec)))
  out=matrix(0,nrow=3,ncol=totcol)
  for (i in 1:(length(vec)-1)) {
    out[1,colloc[i]:colloc[i+1]]=seq(cols[1,vec[i]],cols[1,vec[i+1]],length.out = colloc[i+1]-colloc[i]+1)
    out[2,colloc[i]:colloc[i+1]]=seq(cols[2,vec[i]],cols[2,vec[i+1]],length.out = colloc[i+1]-colloc[i]+1)
    out[3,colloc[i]:colloc[i+1]]=seq(cols[3,vec[i]],cols[3,vec[i+1]],length.out = colloc[i+1]-colloc[i]+1)
  }
  return(out)
}
cols=colfunc(c(1:7,1:7,1:8),limit)
```


#```{r}
cols=matrix(0,3,limit)
colloc=round(seq(1,limit,length.out = 8))
cols[1,1:colloc[3]]=1
cols[1,colloc[3]:colloc[4]]=seq(1,0,length.out = colloc[4]-colloc[3]+1)
cols[1,colloc[6]:colloc[7]]=seq(0,1,length.out = colloc[7]-colloc[6]+1)
cols[1,colloc[7]:limit]=seq(1,0,length.out = limit-colloc[7]+1)
cols[2,1:colloc[2]]=seq(1,0,length.out = colloc[2])
cols[2,colloc[2]:colloc[3]]=seq(0,1,length.out = colloc[3]-colloc[2]+1)
cols[2,colloc[3]:colloc[5]]=1
cols[2,colloc[5]:colloc[6]]=seq(1,0,length.out = colloc[6]-colloc[5]+1)
cols[3,1:colloc[2]]=seq(1,0,length.out = colloc[2])
cols[3,colloc[4]:colloc[5]]=seq(0,1,length.out = colloc[5]-colloc[4]+1)
cols[3,colloc[5]:colloc[7]]=1
cols[3,colloc[7]:limit]=seq(1,0,length.out = limit-colloc[7]+1)
#```

legend
```{r}
legen=array(1,c(legheight+1,width,3))
leghalf=ceiling(legheight/2)
legen[1:(leghalf-1),seq(1,width,length.out = 11),]=0
if (width!=limit) {
  legcol=t(apply(cols,1,function(a){approx(a,n=width)$y}))
} else {
  legcol=cols
}
legen[leghalf,,1]=legcol[1,]
legen[leghalf,,2]=legcol[2,]
legen[leghalf,,3]=legcol[3,]
for (a in 1:(legheight-leghalf)) {
  legen[leghalf+a,,]=legen[leghalf,,]
}
legen[legheight+1,,]=0
```

complex plane
```{r}
complane=function(n,mat=indexmat) {
  rowp=trunc(n/10^ceiling(log10(ncol(mat)+1)))-0.5
  colp=n-(rowp+0.5)*10^ceiling(log10(ncol(mat)+1))-0.5
  real=ctopleft[1]+cwidth*colp
  imag=ctopleft[2]-cheight*rowp
  return(complex(real=real,imaginary = imag))
}
```

mandelbrot function
```{r}
manfunc=function(c,zpow=2,lim=limit) {
  z=0
  mu=1-sqrt(1-4*c)
  if (zpow==2&&sqrt(Re(mu)^2+Im(mu)^2)<1) {
    return(lim)
  } else {
    for (b in 1:lim) {
    iteration=b
    z=z^zpow+c
    if (sqrt(Re(z)^2+Im(z)^2)>2) {
      break
    }
  }
  return(iteration)
  }
}
```

index matrix
```{r}
mandelmat=matrix(0,height,width)
indexmat=row(mandelmat)*10^ceiling(log10(ncol(mandelmat)+1))+col(mandelmat)
```

get color function
```{r}
getcol=function(n,color=cols) {
  return(color[,n])
}
```

split a matrix into equal parts
```{r}
splitmat=function(mat,n,byrow=TRUE) {
  if (byrow) {
    if (n>nrow(mat)) {
      stop("more splits than rows, nrow=",nrow(mat))
    }
    outrows=round(seq(0,nrow(mat),length.out = n+1))
    return(lapply(2:(n+1),function(y){mat[(outrows[y-1]+1):outrows[y],,drop=FALSE]}))
  } else {
    if (n>ncol(mat)) {
      stop("more splits than columns, ncol=",ncol(mnat))
    }
    outcols=round(seq(0,ncol(mat),length.out = n+1))
    return(lapply(2:(n+1),function(y){mat[,(outcols[y-1]+1):outcols[y],drop=FALSE]}))
  }
}
```

super mandelbrot function
```{r}
sumanfunc=function(c,real=mandelmatreal,imag=mandelmatimag,indwidth=ncol(indexmat),lim=limit,sufor=sufor,suadd=suadd,sumult=sumult,suali=suali) { #
  indwidth2=ceiling(log10(indwidth+1))
  creal=round(c-trunc(c/10^indwidth2)*10^indwidth2)
  cimag=round((c-creal)/10^indwidth2)
  creal=real[,creal]
  cimag=imag[,cimag]
  
  zreal=sufor(0,chunks=5)
  zimag=sufor(0,chunks=5)
  for (b in 1:lim) {
    iteration=b
    zreal2=suadd(cbind(sumult(zreal,zreal,chunks=5),sumult(sufor(-1),sumult(zimag,zimag),chunks=5),creal),chunks=5,sual=suali)
    zimag=suadd(cbind(sumult(sufor(2),sumult(zimag,zreal),chunks=5),cimag),chunks=5,sual=suali)
    zreal=zreal2
    zdist=suadd(cbind(sumult(zreal,zreal,chunks=5),sumult(zimag,zimag,chunks=5),sufor(-4,chunks=5)),sual=suali)
    if (all(gsub("-","",zdist)==zdist)) {
      break
    }
  }
  return(b)
}
```

#the zoom
```{r}
setwd("./Mandelbrot Set Output")
ctopleft=starttopleft
cbotright=startbotright
mandif=min((cbotright[1]-ctopleft[1])/(width-1),(ctopleft[2]-cbotright[2])/(height-1))
j=0
coords=matrix(nrow = 0,ncol = 4)
manset=matrix(0,height,width)
indexmat=row(manset)*10^ceiling(log10(ncol(manset+1)))+col(manset)
splindexmat=splitmat(indexmat,5*clusters)
switched=FALSE
clu=makeCluster(clusters)
repeat {
  j=j+1
  if (!switched) {
    mandif=min((cbotright[1]-ctopleft[1])/(width-1),(ctopleft[2]-cbotright[2])/(height-1))
  }
  
  if (!switched&&mandif<1e-13) {
    ctop=sufor(ctopleft[2],chunks=5)
    cright=sufor(cbotright[1],chunks=5)
    cbot=sufor(cbotright[2],chunks=5)
    cleft=sufor(ctopleft[1],chunks=5)
    switched=TRUE
    cat("switched","\n")
  }
  
  if (switched||mandif<1e-13) {
    cwidth=sumult(suadd(cbind(cright,sumult(cleft,sufor(-1),chunks=5))),sufor(1/(width-1)),chunks=5)
    cheight=sumult(suadd(cbind(ctop,sumult(cbot,sufor(-1),chunks=5))),sufor(1/(height-1)),chunks=5)
    mandelmatreal=cbind(cleft,sapply(1:(width-2),function(x){suadd(cbind(cleft,sumult(cwidth,sufor(x),chunks=5)),chunks=5)}),cright)
    mandelmatimag=cbind(cbot,sapply(1:(height-2),function(x){suadd(cbind(cbot,sumult(cheight,sufor(x),chunks=5)),chunks=5)}),ctop)
    manset2=parLapplyLB(clu,splindexmat,function(x,sumanfunc=sumanfunc,mandelmatreal=mandelmatreal,mandelmatimag=mandelmatimag,indexmat=indexmat,limit=limit,sufor=sufor,suadd=suadd,sumult=sumult,suali=suali){apply(x,c(1,2),sumanfunc,real=mandelmatreal,imag=mandelmatimag,indwidth=ncol(indexmat),lim=limit,sufor=sufor,suadd=suadd,sumult=sumult,suali=suali)},sumanfunc=sumanfunc,mandelmatreal=mandelmatreal,mandelmatimag=mandelmatimag,indexmat=indexmat,limit=limit,sufor=sufor,suadd=suadd,sumult=sumult,suali=suali)
    #for (i in 1:prod(dim(indexmat))) {
    #  blatim=Sys.time();bla=sumanfunc(indexmat[i])
    #  cat(i,bla,difftime(Sys.time(),blatim,units="secs"),"\n")
    #}
    manset2=do.call(rbind,manset2)
    
    ctop=suadd(cbind(sumult(suadd(cbind(ctop,sumult(sufor(-1),sufor(endpoint[2]),chunks=5))),sufor(fraction),chunks=5),sufor(endpoint[2],chunks=5)),chunks=5)
    cright=suadd(cbind(sumult(suadd(cbind(cright,sumult(sufor(-1),sufor(endpoint[1]),chunks=5))),sufor(fraction),chunks=5),sufor(endpoint[1],chunks=5)),chunks=5)
    cbot=suadd(cbind(sumult(suadd(cbind(cbot,sumult(sufor(-1),sufor(endpoint[2]),chunks=5))),sufor(fraction),chunks=5),sufor(endpoint[2],chunks=5)),chunks=5)
    cleft=suadd(cbind(sumult(suadd(cbind(cleft,sumult(sufor(-1),sufor(endpoint[1]),chunks=5))),sufor(fraction),chunks=5),sufor(endpoint[1],chunks=5)),chunks=5)
  } else {
    mandelmat=matrix(0,height,width)
mandelmat[1,1]=complane(indexmat[1,1])
mandelmat[1,width]=complane(indexmat[1,width])
mandelmat[height,1]=complane(indexmat[height,1])
mandelmat[height,width]=complane(indexmat[height,width])
mandelmat[1,]=seq(mandelmat[1,1],mandelmat[1,width],length.out = width)
mandelmat[height,]=seq(mandelmat[height,1],mandelmat[height,width],length.out = width)
for (q in 1:width) {
  mandelmat[,q]=seq(mandelmat[1,q],mandelmat[height,q],length.out = height)
}
splmandelmat=splitmat(mandelmat,5*clusters)
manset2=parLapplyLB(clu,splmandelmat,function(x,manfunc=manfunc,limit=limit){apply(x,c(1,2),manfunc,lim=limit)},manfunc=manfunc,limit=limit)
manset2=do.call(rbind,manset2)
#manset2=apply(mandelmat,c(1,2),manfunc)

ctop=(ctopleft[2]-endpoint[2])*fraction+endpoint[2]
  cright=(cbotright[1]-endpoint[1])*fraction+endpoint[1]
  cbot=(cbotright[2]-endpoint[2])*fraction+endpoint[2]
  cleft=(ctopleft[1]-endpoint[1])*fraction+endpoint[1]
  ctopleft=c(cleft,ctop)
cbotright=c(cright,cbot)
  }
  

if (all(manset2==manset)) {
  break
}
manset=manset2
manimg=array(0,c(height,width,3))
manimg=apply(manset,c(1,2),getcol)
manimg=aperm(manimg,c(2,3,1))
manimg=abind(legen,manimg,along = 1)
name=paste0(getwd(),"/Mandelbrot Zoom It ",j,".png")
writePNG(manimg,name)
#coords=rbind(coords,c(ctopleft,cbotright))
cat("Iteration:",j,"topleft:",cleft,ctop,"botright:",cright,cbot,"\n")

}
stopCluster(clu)
gc(verbose = FALSE)
print("Reached end point")
```

saving zoom coordinates
#```{r}
coords=rbind(coords,c(limit,limit,limit,limit))
setwd("./Mandelbrot Set Output")
write.csv(coords,"./Zoom Coordinates.csv")
#```
