---
title: "Mandelbrot"
author: "Bram van Smoorenburg"
date: "20 March 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

#the basics

basic input
```{r}
legheight=10
height=300
width=900
limit=50
```

start
```{r}
if (width>height) {
  starttopleft=c(-2*width/height,2)
  startbotright=c(2*width/height,-2)
} else {
  starttopleft=c(-2,2*height/width)
  startbotright=c(2,-2*height/width)
}
fraction=0.5
```

new directory
```{r}
dir.create("./Mandelbrot Exploration Output")
```

library
```{r}
library(png)
library(abind)
library(grid)
```

legend colors
```{r}
cols=matrix(0,3,limit)
colloc=round(seq(1,limit,length.out = 8))
cols[1,1:colloc[3]]=1
cols[1,colloc[3]:colloc[4]]=seq(1,0,length.out = colloc[4]-colloc[3]+1)
cols[1,colloc[6]:colloc[7]]=seq(0,1,length.out = colloc[7]-colloc[6]+1)
cols[1,colloc[7]:limit]=seq(1,0,length.out = limit-colloc[7]+1)
cols[2,1:colloc[2]]=seq(1,0,length.out = colloc[2])
cols[2,colloc[2]:colloc[3]]=seq(0,1,length.out = colloc[3]-colloc[2]+1)
cols[2,colloc[3]:colloc[5]]=1
cols[2,colloc[5]:colloc[6]]=seq(1,0,length.out = colloc[6]-colloc[5]+1)
cols[3,1:colloc[2]]=seq(1,0,length.out = colloc[2])
cols[3,colloc[4]:colloc[5]]=seq(0,1,length.out = colloc[5]-colloc[4]+1)
cols[3,colloc[5]:colloc[7]]=1
cols[3,colloc[7]:limit]=seq(1,0,length.out = limit-colloc[7]+1)
```

legend
```{r}
legen=array(1,c(legheight+1,width,3))
leghalf=ceiling(legheight/2)
legen[1:(leghalf-1),seq(1,width,length.out = 11),]=0
if (width!=limit) {
  legcol=t(apply(cols,1,function(a){approx(a,n=width)$y}))
} else {
  legcol=cols
}
legen[leghalf,,1]=legcol[1,]
legen[leghalf,,2]=legcol[2,]
legen[leghalf,,3]=legcol[3,]
for (a in 1:(legheight-leghalf)) {
  legen[leghalf+a,,]=legen[leghalf,,]
}
legen[legheight+1,,]=0
```

complex plane
```{r}
complane=function(n,mat=indexmat) {
  rowp=trunc(n/10^ceiling(log10(ncol(mat)+1)))-0.5
  colp=n-(rowp+0.5)*10^ceiling(log10(ncol(mat)+1))-0.5
  real=ctopleft[1]+cwidth*colp
  imag=ctopleft[2]-cheight*rowp
  return(complex(real=real,imaginary = imag))
}
```

mandelbrot function
```{r}
manfunc=function(c,zpow=2,lim=limit) {
  z=0
  loop=FALSE
  mu=1-sqrt(1-4*c)
  if (zpow==2&&sqrt(Re(mu)^2+Im(mu)^2)<1) {
    return(lim)
  } else {
    for (b in 1:lim) {
    iteration=b
    z=z^zpow+c
    if (sqrt(Re(z)^2+Im(z)^2)>2) {
      break
    }
  }
  return(iteration)
  }
}
```

index matrix
```{r}
mandelmat=matrix(0,height,width)
indexmat=row(mandelmat)*10^ceiling(log10(ncol(mandelmat)+1))+col(mandelmat)
```

get color function
```{r}
getcol=function(n,color=cols) {
  return(color[,n])
}
```

split a vector into equal parts
```{r}
splitvec=function(vec,n) {
  if (length(vec)<n) {
    stop("vector not long enough, length:",length(vec))
  }
  out=round(seq(0,length(vec),length.out = n+1))
  return(lapply(2:(n+1),function(y){vec[(out[y-1]+1):out[y]]}))
}
```

and a matrix
```{r}
splitmat=function(mat,n,byrow=TRUE) {
  if (byrow) {
    if (n>nrow(mat)) {
      stop("more splits than rows, nrow=",nrow(mat))
    }
    outrows=round(seq(0,nrow(mat),length.out = n+1))
    return(lapply(2:(n+1),function(y){mat[(outrows[y-1]+1):outrows[y],,drop=FALSE]}))
  } else {
    if (n>ncol(mat)) {
      stop("more splits than columns, ncol=",ncol(mnat))
    }
    outcols=round(seq(0,ncol(mat),length.out = n+1))
    return(lapply(2:(n+1),function(y){mat[,(outcols[y-1]+1):outcols[y],drop=FALSE]}))
  }
}
```

#the zoom
parallel
```{r}
library(parallel)
clusters=6
clu=makeCluster(clusters)
```

```{r}
setwd("./Mandelbrot Exploration Output")
ctopleft=starttopleft
cbotright=startbotright
j=1
coords=matrix(nrow = 0,ncol = 5)
manset=matrix(0,height,width)
cwidth=(cbotright[1]-ctopleft[1])/width
cheight=(ctopleft[2]-cbotright[2])/height
mandelmat=matrix(0,height,width)
mandelmat[1,1]=complane(indexmat[1,1])
mandelmat[1,width]=complane(indexmat[1,width])
mandelmat[height,1]=complane(indexmat[height,1])
mandelmat[height,width]=complane(indexmat[height,width])
mandelmat[1,]=seq(mandelmat[1,1],mandelmat[1,width],length.out = width)
mandelmat[height,]=seq(mandelmat[height,1],mandelmat[height,width],length.out = width)
for (q in 1:width) {
  mandelmat[,q]=seq(mandelmat[1,q],mandelmat[height,q],length.out = height)
}
splmandelmat=splitmat(mandelmat,5*clusters)
manset=parLapplyLB(clu,splmandelmat,function(x,manfunc=manfunc,limit=limit){apply(x,c(1,2),manfunc,lim=limit)},manfunc=manfunc,limit=limit)
manset=do.call(rbind,manset)
#manset=apply(mandelmat,c(1,2),manfunc)
manimg=apply(manset,c(1,2),getcol)
manimg=aperm(manimg,c(2,3,1))
fullimg=abind(legen,manimg,along = 1)
name=paste0(getwd(),"/Mandelbrot Explorer It ",j,".png")
writePNG(fullimg,name)
coords=rbind(coords,c("Start",ctopleft,cbotright))
grid.raster(fullimg)
```

#exploring
commands: zoom, zoom out, left, right, up, down, limit
```{r}
setwd("./Mandelbrot Exploration Output")
repeat {
  com=readline("Please enter command, or type exit to stop: ")
  if (com=="exit") {
    endpoint=c((Re(mandelmat[1,1])+Re(mandelmat[1,width]))/2,(Im(mandelmat[1,1])+Im(mandelmat[height,1]))/2)
coords=rbind(coords,c("End","-",endpoint,"-"))
write.csv(coords,"./Mandelbrot Exploration Coordinates.csv")
stopCluster(clu)
gc()
    break
  } else if (com=="zoom") {
    endpoint=c((Re(mandelmat[1,1])+Re(mandelmat[1,width]))/2,(Im(mandelmat[1,1])+Im(mandelmat[height,1]))/2)
    ctop=(ctopleft[2]-endpoint[2])*fraction+endpoint[2]
  cright=(cbotright[1]-endpoint[1])*fraction+endpoint[1]
  cbot=(cbotright[2]-endpoint[2])*fraction+endpoint[2]
  cleft=(ctopleft[1]-endpoint[1])*fraction+endpoint[1]
  ctopleft=c(cleft,ctop)
cbotright=c(cright,cbot)
cwidth=(cbotright[1]-ctopleft[1])/width
cheight=(ctopleft[2]-cbotright[2])/height
mandelmat=matrix(0,height,width)
mandelmat[1,1]=complane(indexmat[1,1])
mandelmat[1,width]=complane(indexmat[1,width])
mandelmat[height,1]=complane(indexmat[height,1])
mandelmat[height,width]=complane(indexmat[height,width])
mandelmat[1,]=seq(mandelmat[1,1],mandelmat[1,width],length.out = width)
mandelmat[height,]=seq(mandelmat[height,1],mandelmat[height,width],length.out = width)
for (q in 1:width) {
  mandelmat[,q]=seq(mandelmat[1,q],mandelmat[height,q],length.out = height)
}
splmandelmat=splitmat(mandelmat,5*clusters)
manset=parLapplyLB(clu,splmandelmat,function(x,manfunc=manfunc,limit=limit){apply(x,c(1,2),manfunc,lim=limit)},manfunc=manfunc,limit=limit)
manset=do.call(rbind,manset)
#manset=apply(mandelmat,c(1,2),manfunc)
manimg=apply(manset,c(1,2),getcol)
manimg=aperm(manimg,c(2,3,1))
fullimg=abind(legen,manimg,along = 1)
j=j+1
name=paste0(getwd(),"/Mandelbrot Explorer It ",j,".png")
writePNG(fullimg,name)
coords=rbind(coords,c("Zoom in",ctopleft,cbotright))
grid.raster(fullimg)
  } else if (com=="zoom out") {
    endpoint=c((Re(mandelmat[1,1])+Re(mandelmat[1,width]))/2,(Im(mandelmat[1,1])+Im(mandelmat[height,1]))/2)
    ctop=(ctopleft[2]-endpoint[2])/fraction+endpoint[2]
  cright=(cbotright[1]-endpoint[1])/fraction+endpoint[1]
  cbot=(cbotright[2]-endpoint[2])/fraction+endpoint[2]
  cleft=(ctopleft[1]-endpoint[1])/fraction+endpoint[1]
  ctopleft=c(cleft,ctop)
cbotright=c(cright,cbot)
cwidth=(cbotright[1]-ctopleft[1])/width
cheight=(ctopleft[2]-cbotright[2])/height
mandelmat=matrix(0,height,width)
mandelmat[1,1]=complane(indexmat[1,1])
mandelmat[1,width]=complane(indexmat[1,width])
mandelmat[height,1]=complane(indexmat[height,1])
mandelmat[height,width]=complane(indexmat[height,width])
mandelmat[1,]=seq(mandelmat[1,1],mandelmat[1,width],length.out = width)
mandelmat[height,]=seq(mandelmat[height,1],mandelmat[height,width],length.out = width)
for (q in 1:width) {
  mandelmat[,q]=seq(mandelmat[1,q],mandelmat[height,q],length.out = height)
}
splmandelmat=splitmat(mandelmat,5*clusters)
manset=parLapplyLB(clu,splmandelmat,function(x,manfunc=manfunc,limit=limit){apply(x,c(1,2),manfunc,lim=limit)},manfunc=manfunc,limit=limit)
manset=do.call(rbind,manset)
#manset=apply(mandelmat,c(1,2),manfunc)
manimg=apply(manset,c(1,2),getcol)
manimg=aperm(manimg,c(2,3,1))
fullimg=abind(legen,manimg,along = 1)
j=j+1
name=paste0(getwd(),"/Mandelbrot Explorer It ",j,".png")
writePNG(fullimg,name)
coords=rbind(coords,c("Zoom Out",ctopleft,cbotright))
grid.raster(fullimg)
  } else if (com=="left") {
    mandif=Re(mandelmat[1,(width/2)+1]-mandelmat[1,1])
    ctopleft[1]=ctopleft[1]-mandif
    cbotright[1]=cbotright[1]-mandif
    mandelmat2=mandelmat[,1:(width/2)]-mandif
    mandelmat=cbind(mandelmat2,mandelmat[,1:(width/2)])
    splmandelmat=splitmat(mandelmat2,5*clusters)
manset2=parLapplyLB(clu,splmandelmat,function(x,manfunc=manfunc,limit=limit){apply(x,c(1,2),manfunc,lim=limit)},manfunc=manfunc,limit=limit)
manset2=do.call(rbind,manset2)
    #manset2=apply(mandelmat2,c(1,2),manfunc)
    manset=cbind(manset2,manset[,1:(width/2)])
    manimg2=apply(manset2,c(1,2),getcol)
    manimg2=aperm(manimg2,c(2,3,1))
    manimg=abind(manimg2,manimg[,1:(width/2),],along = 2)
fullimg=abind(legen,manimg,along = 1)
j=j+1
name=paste0(getwd(),"/Mandelbrot Explorer It ",j,".png")
writePNG(fullimg,name)
coords=rbind(coords,c("Left",ctopleft,cbotright))
grid.raster(fullimg)
  } else if (com=="right") {
    mandif=Re(mandelmat[1,(width/2)+1]-mandelmat[1,1])
    ctopleft[1]=ctopleft[1]+mandif
    cbotright[1]=cbotright[1]+mandif
    mandelmat2=mandelmat[,(width/2+1):width]+mandif
    mandelmat=cbind(mandelmat[,(width/2+1):width],mandelmat2)
    splmandelmat=splitmat(mandelmat2,5*clusters)
manset2=parLapplyLB(clu,splmandelmat,function(x,manfunc=manfunc,limit=limit){apply(x,c(1,2),manfunc,lim=limit)},manfunc=manfunc,limit=limit)
manset2=do.call(rbind,manset2)
    #manset2=apply(mandelmat2,c(1,2),manfunc)
    manset=cbind(manset[,(width/2+1):width],manset2)
    manimg2=apply(manset2,c(1,2),getcol)
    manimg2=aperm(manimg2,c(2,3,1))
    manimg=abind(manimg[,(width/2+1):width,],manimg2,along = 2)
fullimg=abind(legen,manimg,along = 1)
j=j+1
name=paste0(getwd(),"/Mandelbrot Explorer It ",j,".png")
writePNG(fullimg,name)
coords=rbind(coords,c("Right",ctopleft,cbotright))
grid.raster(fullimg)
  } else if (com=="up") {
    mandif=mandelmat[1,1]-mandelmat[height/2+1,1]
    ctopleft[2]=ctopleft[2]+Im(mandif)
    cbotright[2]=cbotright[2]+Im(mandif)
    mandelmat2=mandelmat[1:(height/2),]+mandif
    mandelmat=rbind(mandelmat2,mandelmat[1:(height/2),])
    splmandelmat=splitmat(mandelmat2,5*clusters)
manset2=parLapplyLB(clu,splmandelmat,function(x,manfunc=manfunc,limit=limit){apply(x,c(1,2),manfunc,lim=limit)},manfunc=manfunc,limit=limit)
manset2=do.call(rbind,manset2)
    #manset2=apply(mandelmat2,c(1,2),manfunc)
    manset=rbind(manset2,manset[1:(height/2),])
    manimg2=apply(manset2,c(1,2),getcol)
    manimg2=aperm(manimg2,c(2,3,1))
    manimg=abind(manimg2,manimg[1:(height/2),,],along = 1)
fullimg=abind(legen,manimg,along = 1)
j=j+1
name=paste0(getwd(),"/Mandelbrot Explorer It ",j,".png")
writePNG(fullimg,name)
coords=rbind(coords,c("Up",ctopleft,cbotright))
grid.raster(fullimg)
  } else if (com=="down") {
    mandif=mandelmat[1,1]-mandelmat[height/2+1,1]
    ctopleft[2]=ctopleft[2]-Im(mandif)
    cbotright[2]=cbotright[2]-Im(mandif)
    mandelmat2=mandelmat[(height/2+1):height,]-mandif
    mandelmat=rbind(mandelmat[(height/2+1):height,],mandelmat2)
    splmandelmat=splitmat(mandelmat2,5*clusters)
manset2=parLapplyLB(clu,splmandelmat,function(x,manfunc=manfunc,limit=limit){apply(x,c(1,2),manfunc,lim=limit)},manfunc=manfunc,limit=limit)
manset2=do.call(rbind,manset2)
    #manset2=apply(mandelmat2,c(1,2),manfunc)
    manset=rbind(manset[(height/2+1):height,],manset2)
    manimg2=apply(manset2,c(1,2),getcol)
    manimg2=aperm(manimg2,c(2,3,1))
    manimg=abind(manimg[(height/2+1):height,,],manimg2,along = 1)
fullimg=abind(legen,manimg,along = 1)
j=j+1
name=paste0(getwd(),"/Mandelbrot Explorer It ",j,".png")
writePNG(fullimg,name)
coords=rbind(coords,c("Down",ctopleft,cbotright))
grid.raster(fullimg)
  } else if (com=="limit") {
    newlim=readline("New limit: ")
    oldlim=limit
    limit=as.numeric(newlim)
    cols=matrix(0,3,limit)
colloc=round(seq(1,limit,length.out = 8))
cols[1,1:colloc[3]]=1
cols[1,colloc[3]:colloc[4]]=seq(1,0,length.out = colloc[4]-colloc[3]+1)
cols[1,colloc[6]:colloc[7]]=seq(0,1,length.out = colloc[7]-colloc[6]+1)
cols[1,colloc[7]:limit]=seq(1,0,length.out = limit-colloc[7]+1)
cols[2,1:colloc[2]]=seq(1,0,length.out = colloc[2])
cols[2,colloc[2]:colloc[3]]=seq(0,1,length.out = colloc[3]-colloc[2]+1)
cols[2,colloc[3]:colloc[5]]=1
cols[2,colloc[5]:colloc[6]]=seq(1,0,length.out = colloc[6]-colloc[5]+1)
cols[3,1:colloc[2]]=seq(1,0,length.out = colloc[2])
cols[3,colloc[4]:colloc[5]]=seq(0,1,length.out = colloc[5]-colloc[4]+1)
cols[3,colloc[5]:colloc[7]]=1
cols[3,colloc[7]:limit]=seq(1,0,length.out = limit-colloc[7]+1)
legen=array(1,c(legheight+1,width,3))
leghalf=ceiling(legheight/2)
legen[1:(leghalf-1),seq(1,width,length.out = 11),]=0
if (width!=limit) {
  legcol=t(apply(cols,1,function(a){approx(a,n=width)$y}))
} else {
  legcol=cols
}
legen[leghalf,,1]=legcol[1,]
legen[leghalf,,2]=legcol[2,]
legen[leghalf,,3]=legcol[3,]
for (a in 1:(legheight-leghalf)) {
  legen[leghalf+a,,]=legen[leghalf,,]
}
legen[legheight+1,,]=0
if (limit>oldlim) {
  whichlim=which(manset==oldlim)
  mandelmat2=mandelmat[whichlim]
  splmandelmat=splitvec(mandelmat2,clusters)
  manset[whichlim]=unlist(parSapply(clu,splmandelmat,function(x,manfunc=manfunc,limit=limit){sapply(x,manfunc,lim=limit)},manfunc=manfunc,limit=limit))
  #manset[whichlim]=sapply(mandelmat2,manfunc)
  manimg=apply(manset,c(1,2),getcol)
manimg=aperm(manimg,c(2,3,1))
fullimg=abind(legen,manimg,along = 1)
j=j+1
name=paste0(getwd(),"/Mandelbrot Explorer It ",j,".png")
writePNG(fullimg,name)
coords=rbind(coords,c("Change limit",ctopleft,cbotright))
grid.raster(fullimg)
} else {
  manset[which(manset>limit)]=limit
  manimg=apply(manset,c(1,2),getcol)
manimg=aperm(manimg,c(2,3,1))
fullimg=abind(legen,manimg,along = 1)
j=j+1
name=paste0(getwd(),"/Mandelbrot Explorer It ",j,".png")
writePNG(fullimg,name)
coords=rbind(coords,c("Change limit",ctopleft,cbotright))
grid.raster(fullimg)
}
  } else {
    cat("Didn't understand command, please try again.")
  }
}
```
